/**
 * Colour schemes: which colour sits on which face.
 *
 * A cube's scheme is fixed by choosing two adjacent faces — say white on top and
 * red in front — because the handedness of a real cube then determines the other
 * four. Rather than encode that handedness by hand (easy to get mirrored), the
 * 24 valid schemes are generated by rotating the standard one, so every scheme
 * offered is reachable from a real cube by turning it in your hands.
 *
 * Face letters stay positions, never colours, so none of this touches the model
 * or the notation — it is purely what gets painted.
 */

import { FACES, FACE_NORMALS, applyMat } from './cube.js';
import { rotationMatrix } from './moves.js';

export const COLOR_NAMES = ['white', 'yellow', 'green', 'blue', 'red', 'orange'];

export const OPPOSITE = {
  white: 'yellow',
  yellow: 'white',
  green: 'blue',
  blue: 'green',
  red: 'orange',
  orange: 'red',
};

/** The WCA standard: white up, green front, red right. */
const STANDARD = { U: 'white', D: 'yellow', F: 'green', B: 'blue', R: 'red', L: 'orange' };

const NORMAL_TO_FACE = {};
for (const face of FACES) NORMAL_TO_FACE[FACE_NORMALS[face].join(',')] = face;

function rotateScheme(scheme, matrix) {
  const out = {};
  for (const face of FACES) {
    const moved = NORMAL_TO_FACE[applyMat(matrix, FACE_NORMALS[face]).join(',')];
    out[moved] = scheme[face];
  }
  return out;
}

/** All 24 orientations of the standard cube, found by turning it every way. */
export const ALL_SCHEMES = (() => {
  const identify = (s) => FACES.map((f) => s[f]).join(',');
  const found = new Map([[identify(STANDARD), STANDARD]]);
  const generators = ['x', 'y', 'z'].map((axis) => rotationMatrix(axis, 1));

  const queue = [STANDARD];
  while (queue.length) {
    const scheme = queue.shift();
    for (const matrix of generators) {
      const next = rotateScheme(scheme, matrix);
      const id = identify(next);
      if (!found.has(id)) {
        found.set(id, next);
        queue.push(next);
      }
    }
  }
  return [...found.values()];
})();

/** Which colours can sit in front given the top: everything but it and its opposite. */
export function validFronts(top) {
  return ALL_SCHEMES.filter((s) => s.U === top).map((s) => s.F);
}

/**
 * The full face-to-colour map for a chosen top and front, or null if those two
 * cannot be adjacent on a real cube.
 */
export function schemeFor(top, front) {
  return ALL_SCHEMES.find((s) => s.U === top && s.F === front) ?? null;
}

/** Nearest valid scheme, for when a stored preference no longer makes sense. */
export function resolveScheme(top, front) {
  const exact = schemeFor(top, front);
  if (exact) return { top, front, scheme: exact };

  const safeTop = COLOR_NAMES.includes(top) ? top : 'white';
  const safeFront = validFronts(safeTop)[0];
  return { top: safeTop, front: safeFront, scheme: schemeFor(safeTop, safeFront) };
}
